version: '3.8'

services:
  web:
    build: .
    networks:
      phish-network:
    volumes:
      - app:/app
  nginx:
    image: nginx
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
    networks:
      phish-network:
    ports:
      - "80:80" 

networks:
  phish-network:

volumes:
  app:
