services:
  web:
    build: .
    networks:
      phish-network:
    volumes:
      - db:/app/db.sqlite3
    restart: on-failure
 
  nginx:
    image: nginx
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
      - nginx:/etc/nginx
    networks:
      phish-network:
    ports:
      - "80:80" 



networks:
  phish-network:
    ipam:
      config:
        - subnet: 10.0.0.0/24

volumes:
  data:
  nginx:
