services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: phishing
      MYSQL_USER: phisher
      MYSQL_PASSWORD: user_password
    volumes:
      - data:/var/lib/mysql
    network_mode: host

volumes:
  data:
