# Generated by Django 5.1.2 on 2024-10-20 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_name_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
